<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Branch Code or Routing Number_branch_code</name>
   <tag></tag>
   <elementGuidId>326d50ca-4f16-4914-bc01-7589c75223c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_branch_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_branch_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9106697d-1b9f-4a8c-8e85-efe3aa1184ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>058ea80a-1561-48a8-a631-214ce5309a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84a75f7e-e74b-45c9-9e6b-f01500cc2f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control error</value>
      <webElementGuid>58126597-3088-42d3-80ee-a31385223085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_branch_code</value>
      <webElementGuid>13efa32f-b39b-4f32-8f4e-14f1931b1208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branch_code</value>
      <webElementGuid>e39b12e2-81d3-4c08-9ce8-2d40a7fabd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_branch_code&quot;)</value>
      <webElementGuid>1e0e5623-c322-4c41-9087-a8ce37de73a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_branch_code']</value>
      <webElementGuid>fb465a2a-0c7d-4473-9316-c47168427304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[2]/div[6]/div/input</value>
      <webElementGuid>41e3122b-c712-415e-9fec-90ceed99e95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[6]/div/input</value>
      <webElementGuid>72722375-f9d2-441c-ae5a-40dc5d38277c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'input_branch_code' and @name = 'branch_code']</value>
      <webElementGuid>adce4e6a-c94b-4fd8-b546-4b3001ceaa73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
