<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_form-control minor-edit _a4e6be</name>
   <tag></tag>
   <elementGuidId>7fb730f1-497c-434f-8c29-30111c494cd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#step-2 > div.panel-body.col-sm-12 > div.form-group.pay-form > div.col-sm-8 > div.iti.iti--allow-dropdown.iti--separate-dial-code > input.form-control.minor-edit.int_tel_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afecce67-21ab-4e18-be06-db1d1ca8f7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>f4be8448-17d8-4814-9926-09a7999e836d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80b5151a-5719-4db9-a804-28c8e8724e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control minor-edit int_tel_input</value>
      <webElementGuid>14a07c5d-0b5d-47a1-a3a0-b07d1177231b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>59d4eee3-c58b-4ebf-8de8-8671d5c5f6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>e15b88a9-9581-462e-9377-aec9bbc44552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>intl-1</value>
      <webElementGuid>9a6172f4-5131-404b-9e7e-9eafce1e3b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812-345-678</value>
      <webElementGuid>31e3085f-0206-4602-96d7-e97bdecacece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>eff3c01d-e51a-4947-a62b-2045be40e53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-2&quot;)/div[@class=&quot;panel-body col-sm-12&quot;]/div[@class=&quot;form-group pay-form&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/input[@class=&quot;form-control minor-edit int_tel_input&quot;]</value>
      <webElementGuid>a8f8ef1f-dca1-462b-a28c-f9c89ba0cd07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[17]</value>
      <webElementGuid>9ba4a7e8-968d-4f97-80fc-1d6ae2fc4ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div[2]/div[5]/div/div/input</value>
      <webElementGuid>db36814a-fdf4-4b03-a9b5-0a142002deb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/div/input</value>
      <webElementGuid>1a8cb5d9-2f41-4516-97e0-439a9a5c0078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '812-345-678']</value>
      <webElementGuid>244c3465-6672-4b70-a064-40508520ef42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
