<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referral_referral_general</name>
   <tag></tag>
   <elementGuidId>b645dc2c-84ae-43a9-a0fd-eefc151c15e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='referral_general']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#referral_general</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05786b06-f1a5-4fcf-ba4f-86f2334ff2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>673e7a94-c16e-4d99-a3d5-4e956a3cb760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58bf8262-d74b-479c-844c-4b38202b0ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control error</value>
      <webElementGuid>6a0982ea-d7d2-407e-93b7-708066169848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referral_general</value>
      <webElementGuid>de071c42-c92a-4db2-a1dc-c244182ec7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>referral_general</value>
      <webElementGuid>eb80c187-c0f0-4710-92de-86a66c61050c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your referral</value>
      <webElementGuid>3dea76a9-d753-4c01-b7be-d8bccfb0e807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referral_general&quot;)</value>
      <webElementGuid>e38f3e73-8049-4f56-af46-9c557b5a32ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='referral_general']</value>
      <webElementGuid>e2c4f672-92b6-4464-a0e1-34dcb4babf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-1']/div[2]/div/div[2]/input</value>
      <webElementGuid>5dd27e89-a8c0-4b8b-96c9-ffd7c7355c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>87fb6755-a7b4-451d-83de-d81d2eb19323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'referral_general' and @name = 'referral_general' and @placeholder = 'Enter your referral']</value>
      <webElementGuid>8a4c9051-8177-4dc6-9f99-eb8484481384</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
