<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>0d1c37ec-aab6-48af-a82b-40f5f0fd68f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='send-docs-via-email-field']/div/div/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.switch-off > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>de46284e-0053-4dd2-905d-cd4933b14531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>b3a497f7-4dd6-4d66-94df-9c289273fc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send-docs-via-email-field&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;switch has-switches&quot;]/div[@class=&quot;switch-on&quot;]/div[@class=&quot;switch has-switches&quot;]/div[@class=&quot;switch-off&quot;]/label[1]</value>
      <webElementGuid>9d153e26-5159-4ced-875e-0b5c1efe6979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='send-docs-via-email-field']/div/div/div/div/div/label</value>
      <webElementGuid>9e079c9e-eb94-4faf-acb9-ba82ce792729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[1]/following::label[1]</value>
      <webElementGuid>f4f6518d-8e6f-4f88-baae-55251aeec5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send documents via email'])[1]/following::label[1]</value>
      <webElementGuid>86638d85-7494-4923-93b9-1297bb124212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::label[1]</value>
      <webElementGuid>4226953e-f579-4cac-b1d6-5bde42ef9335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::label[1]</value>
      <webElementGuid>d2cd4878-8be0-4858-aa93-25412e4c4d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/label</value>
      <webElementGuid>c2ce00c0-c770-4b30-ae2c-2e8ba85e8d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>ac634d8d-72ca-420c-818b-9c20e31fc95a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
