<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Special Instructions (Optional)_in_1d0905</name>
   <tag></tag>
   <elementGuidId>3515d9e7-36d1-4c86-ac2f-47dcf6c65457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputInstructions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputInstructions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8126f4bb-643f-4767-96db-31b5bad66a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>__away</value>
      <webElementGuid>86bd3d62-6180-4998-8b37-ee7c416ffa1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4e9b2bb2-04f2-4a1d-bd1a-a17c3ba0a245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1a7158d4-4085-4316-8ad3-54bcdbbf68ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control no-resize</value>
      <webElementGuid>8152df75-4de6-45c9-b3ff-d99ac2f54b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputInstructions</value>
      <webElementGuid>f7ed7e05-19cc-4ba5-8152-d06b84155ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>instructions</value>
      <webElementGuid>d29cf861-280f-4505-82d2-e26484a96c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputInstructions&quot;)</value>
      <webElementGuid>ee45849f-857e-4752-862c-9ef5d1421d88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputInstructions']</value>
      <webElementGuid>4ad83e2d-a430-4aee-888f-6a4ff7589cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/div[2]/div[8]/div/textarea</value>
      <webElementGuid>70884a58-3014-42c8-895d-8f8b761a1460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/textarea</value>
      <webElementGuid>8e3feaa0-ec01-4184-afb0-9ce6d9afb265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'inputInstructions' and @name = 'instructions']</value>
      <webElementGuid>81bf6674-48a8-4ac7-8f4d-8d63bd669474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
