<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_By clicking this box, I accept the,an_f76ab8</name>
   <tag></tag>
   <elementGuidId>2d19eecf-dbc9-458b-851f-5b67c8bf6a77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.psa-checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e7c2cef-a046-492b-9e05-1cd62852c22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4e30f663-6854-415e-b86d-cdfccbbb4b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>psa-checkbox</value>
      <webElementGuid>87a81c71-df5a-4939-b24d-000791f6651f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRegister&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 register-row psa-aggrement&quot;]/input[@class=&quot;psa-checkbox&quot;]</value>
      <webElementGuid>3b742c21-15e0-4098-aaf6-13e2049f8cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>e62168a8-f379-4715-9563-de330094d347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[6]/div/input</value>
      <webElementGuid>2247f6a0-2246-429a-bd51-32e0a5d3e39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>11548d19-d6aa-4ad8-900b-b021e8c4e941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>2ef295cb-c64c-40b1-9fb4-5f93704bc312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
