<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Your state  province (optional)nullE_5336fa</name>
   <tag></tag>
   <elementGuidId>71395a8b-a79d-4447-9491-38356925e304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='states']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#states</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>369ea964-04ac-4396-9faa-32ca02d1a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>state</value>
      <webElementGuid>b6ea0da8-b784-4b80-b0bc-3e2dc99ec07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>84d3c5fc-a354-4115-8007-82e3daa9f7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>677ab871-8cce-4979-8706-57e9afff6c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your state / province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape</value>
      <webElementGuid>3bd2c7e3-a815-42f8-8be5-d04284825728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;states&quot;)</value>
      <webElementGuid>b83d0788-08e8-4573-b964-c8c5a8bb8a71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='states']</value>
      <webElementGuid>7f4049f2-b48a-45c9-a87e-450328ec1a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='state_input_wrapper']/select</value>
      <webElementGuid>9dd4e98f-5fd3-4233-b105-1781967e80d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[1]/following::select[2]</value>
      <webElementGuid>5e2ee60d-f505-49ae-a0ff-f226d6b1b024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::select[2]</value>
      <webElementGuid>7d3cc6ea-4122-48eb-90ee-1514cd0d0666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Services Agreement'])[1]/preceding::select[1]</value>
      <webElementGuid>22fcd187-f901-4249-886f-2ad0baa4a99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='null']/parent::*</value>
      <webElementGuid>919f0533-c6bf-437a-b391-00f009fb94ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>3280cfbc-374a-4172-86d6-38d187cd237a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'state' and @id = 'states' and (text() = 'Your state / province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape' or . = 'Your state / province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape')]</value>
      <webElementGuid>16ca05a4-df92-4d19-b39d-8c486033cc5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
