<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your state  province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape</name>
   <tag></tag>
   <elementGuidId>c0a2ba39-0a48-4b46-9071-e6bf69b2756e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='state_input_wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#state_input_wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cacdfc71-02ac-4e8c-b0c1-4d3ad7773b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6 register-row</value>
      <webElementGuid>cd26cebd-ae80-49fc-bc0a-0b71faae2b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>state_input_wrapper</value>
      <webElementGuid>8d638001-da4c-4090-825c-9f1e2c1a3ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your state / province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape</value>
      <webElementGuid>81fb071c-bdb3-4c90-83d0-92806f8a01f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;state_input_wrapper&quot;)</value>
      <webElementGuid>d282562b-ca0a-47a8-aade-00f01a39ae2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='state_input_wrapper']</value>
      <webElementGuid>6b0608a2-3e94-49eb-897d-75da6b7496c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[5]/div[4]</value>
      <webElementGuid>8bb3a713-ca6e-4fd3-87f4-a0f0a90e3b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Åland Islands'])[1]/following::div[2]</value>
      <webElementGuid>68b04686-3743-47ec-b2d6-feb8b3edee30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[1]/following::div[4]</value>
      <webElementGuid>0ffe9454-0784-44d1-9db3-97e049528e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]</value>
      <webElementGuid>fe9f0d17-58dc-40c7-acd2-96ae61f0e16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'state_input_wrapper' and (text() = 'Your state / province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape' or . = 'Your state / province (optional)nullEastern CapeFree StateGautengKwaZulu-NatalLimpopoMpumalangaNorthern CapeNorth WestWestern Cape')]</value>
      <webElementGuid>9802c752-bb4e-442f-9f04-1f912e35bcfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
