<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login_signatory_last_name</name>
   <tag></tag>
   <elementGuidId>ab934041-7e79-45e6-ba8a-d96bfffc68ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signatory_last_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signatory_last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>791aa3a4-a06b-41cd-aa5d-2e7f1488f3ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cac3c179-a943-4695-9937-8e1e65887888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signatory_last_name</value>
      <webElementGuid>73a0b560-45a1-455b-ac6f-eb98e6b33096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border-grey</value>
      <webElementGuid>c10d4441-758b-4932-bb7f-4eacbaa1a3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signatory_last_name</value>
      <webElementGuid>58d0a2f8-9328-4ece-b911-f226e2c64b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last name</value>
      <webElementGuid>8866dfeb-4b12-4fcd-903d-a3745567229e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4b99ef41-d1ea-4500-8135-f6b9c646c4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>c2646a1a-c74c-4326-9d55-11f02e3ffa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signatory_last_name&quot;)</value>
      <webElementGuid>c4c95b76-b92a-4684-b31d-e963092066e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signatory_last_name']</value>
      <webElementGuid>7fc8bee5-2728-4cec-a94a-ace41d29f317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[3]/div[2]/input</value>
      <webElementGuid>fae6512b-e0f4-4292-b97e-43ca4f875f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>abe90b1f-7c05-4491-a12e-7753e9dd51e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'signatory_last_name' and @id = 'signatory_last_name' and @placeholder = 'Last name']</value>
      <webElementGuid>2c325f85-6616-4fca-adf7-86ef72994175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
