<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_questions30</name>
   <tag></tag>
   <elementGuidId>80738c5f-2026-40c1-ae63-cc787e9cb0e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='questions[30]'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>679c3734-30cc-4a93-bb02-0035189d173d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-check</value>
      <webElementGuid>209ae4ca-a2dd-45e0-bdf4-cb81245feca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d3421745-edf6-4e12-8e25-6cb0d7d46f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>questions[30]</value>
      <webElementGuid>5dd9b044-438e-43e8-abd4-3bb0695a8d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>179ba3ea-75fd-43e1-9e0c-9cd4a789e4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>674e55de-06ba-4e26-bb61-56945698f8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/section[@class=&quot;wrapper&quot;]/div[@class=&quot;row space-bottom&quot;]/div[@class=&quot;col-lg-12&quot;]/section[@class=&quot;panel container container-md&quot;]/form[@class=&quot;form-horizontal tasi-form&quot;]/div[@class=&quot;panel-body panel-padding&quot;]/div[@class=&quot;form-group pay-form&quot;]/div[@class=&quot;row question-item&quot;]/div[@class=&quot;col-sm-12&quot;]/label[@class=&quot;radio-inline&quot;]/input[@class=&quot;radio-check&quot;]</value>
      <webElementGuid>bbb05e3c-fc55-4660-8fa5-b485128722af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='questions[30]'])[2]</value>
      <webElementGuid>90023775-4b56-4cff-9f6b-6710a7f3e97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div/div/section/form/div/div[2]/div[2]/div[2]/label[2]/input</value>
      <webElementGuid>fd060305-ad01-4f13-acb2-5663c30c1d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label[2]/input</value>
      <webElementGuid>3439ee54-9df9-4bdb-992c-248a832ca04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'questions[30]']</value>
      <webElementGuid>9cb6d339-ea2e-43db-b21e-e02327e9e75b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
