<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Projected annual volume_questions33</name>
   <tag></tag>
   <elementGuidId>af2a3b83-fcfa-4fcc-a046-3f8ebf3d7fcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='questions[33]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;questions[33]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49d58c1b-c03e-4d55-a8fa-21dc22f3ea99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8dcf33bf-fbc7-4a44-bc5d-a8837daa0a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>83f2578c-bed0-450c-a830-0d946a8aadf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>questions[33]</value>
      <webElementGuid>08f8e710-1ede-41b7-8df5-a4491707d881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>R 0.00</value>
      <webElementGuid>90937b22-6dd5-4f13-b913-fe85f81d0e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9350c406-f15f-4a7c-bca5-60667a14ffa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>6f57a30a-4769-479e-ba68-61e9a6fe7f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/section[@class=&quot;wrapper&quot;]/div[@class=&quot;row space-bottom&quot;]/div[@class=&quot;col-lg-12&quot;]/section[@class=&quot;panel container container-md&quot;]/form[@class=&quot;form-horizontal tasi-form&quot;]/div[@class=&quot;panel-body panel-padding&quot;]/div[@class=&quot;form-group pay-form&quot;]/div[@class=&quot;row question-item&quot;]/div[@class=&quot;col-sm-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>908ae7a3-f55a-4604-aa5d-f663781a4b3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='questions[33]']</value>
      <webElementGuid>902b9549-09da-4637-b44f-9ea62cffdee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div/div/section/form/div/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>4f741aa8-58b8-4b87-915d-a664daa81577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e19f7df5-c8b7-46de-86ee-a696d55a0518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'questions[33]' and @placeholder = 'R 0.00']</value>
      <webElementGuid>15447fa6-bb68-415f-bf24-0b6ed2753efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
