<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Yes</name>
   <tag></tag>
   <elementGuidId>78a0b6aa-a06c-4f06-8f9f-dd704a4bb7ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/section/div/div/section/form/div/div[2]/div/div[2]/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b56de96c-7714-4124-9a83-a3a4e036c0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-inline</value>
      <webElementGuid>ed00ec64-ed02-4f8d-a4bd-dcacaebf799d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Yes</value>
      <webElementGuid>a3657dbe-33fe-46c7-a54c-8e664b53ae82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/section[@class=&quot;wrapper&quot;]/div[@class=&quot;row space-bottom&quot;]/div[@class=&quot;col-lg-12&quot;]/section[@class=&quot;panel container container-md&quot;]/form[@class=&quot;form-horizontal tasi-form&quot;]/div[@class=&quot;panel-body panel-padding&quot;]/div[@class=&quot;form-group pay-form&quot;]/div[@class=&quot;row question-item&quot;]/div[@class=&quot;col-sm-12&quot;]/label[@class=&quot;radio-inline&quot;]</value>
      <webElementGuid>b166fca5-47e6-4bff-b056-8fd3fc212536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/section/div/div/section/form/div/div[2]/div/div[2]/label[2]</value>
      <webElementGuid>c9f6d732-68b2-4a6f-98b4-79e82cc3481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/following::label[1]</value>
      <webElementGuid>480edacc-bdb1-457e-a2a9-35872dd44159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you ship your own products?'])[1]/following::label[2]</value>
      <webElementGuid>c0e7d948-b2f9-4c57-9f6e-7d6498d0ed17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you sell physical products?'])[1]/preceding::label[1]</value>
      <webElementGuid>df08f991-5a47-4f7a-a5e2-13dc2e91b276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/preceding::label[1]</value>
      <webElementGuid>4c7066b5-797d-4534-9cd1-3318df699e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>8eacaec1-0e95-4ffc-be66-c8ab1b1f1c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Yes' or . = ' Yes')]</value>
      <webElementGuid>5f7eb2ae-ec77-42d7-b3b1-47ed02dc8512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
